### ISSUE TITLE
add animalavatar to huggingface hub

### ISSUE THREAD

**Issue by jadechoghari** [facebookresearch/AnimalAvatar#1]
A model for animals finally 🤩.
Can I add the model and make it compatible with Hugging Face 🤗?
It's not yet included.

Goal: Make AI open and accessible to all!

**Comment by RemySabathier** [comment]
Hi, thanks for your interest in our project !
I think Hugging Face is more adapted to feed-forward models, since our solution is based on an optimization-loop, I don't think it can fit there.
However, if you think of a feature in particular let me know, I'd be glad to help.

**Comment by jadechoghari** [comment]
Ok I'll let you know, thanks!

**Comment by jadechoghari** [comment]
@RemySabathier i just want to point out: If you have any pre-trained models trained with this framework it would be nice to host those models and have demos as well!!
