### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by LarkLeeOnePiece** [facebookresearch/AnimalAvatar#3]
Fantastic work! How can I get the videos of the dogs that you used in the paper.

**Comment by RemySabathier** [comment]
Hey thanks, we use COP3D that you can download here: https://github.com/facebookresearch/cop3d.
We also provide the subset of sequence IDs in COP3D that we use for all our visualizations in our code at config/keys.py : "subsetcop3d"

**Comment by LarkLeeOnePiece** [comment]
One more question, can you tell me what are  the squence number of the dataset from cop3d that you used fot testing. There are so many dog data in the cop3d.

**Comment by RemySabathier** [comment]
You can find our subset of COP3D sequences in our code implementation here: https://github.com/facebookresearch/AnimalAvatar/blob/5da400355157457ab3ac26a0f2d547912c80fee0/config/keys.py#L54

**Comment by LarkLeeOnePiece** [comment]
Thank you so much!

**Comment by Gracezxw** [comment]
You mentioned in your paper that you "select a subset of 50 dog videos". But why are there only 40 sequence numbers in config/keys.py : "subsetcop3d"?



> You can find our subset of COP3D sequences in our code implementation here:
> 
> https://github.com/facebookresearch/AnimalAvatar/blob/5da400355157457ab3ac26a0f2d547912c80fee0/config/keys.py#L54
