### ISSUE TITLE
AttributeError: 'DensePoseChartPredictorOutputWithConfidences' object has no attribute 'embedding'

### ISSUE THREAD

**Issue by Gracezxw** [facebookresearch/AnimalAvatar#6]
Thanks for your excellent work!

After following exactly the installation instructions, I met the following error during the preprocessing phrase:
```
Traceback (most recent call last):
  File "/mnt/cvda/animal3d/code/AnimalAvatar/main_preprocess_scene.py", line 67, in <module>
    preprocess_sequence(
  File "/mnt/cvda/animal3d/code/AnimalAvatar/main_preprocess_scene.py", line 29, in preprocess_sequence
    preprocess_cse(sequence_index, dataset_source, preprocess_path_cse)
  File "/mnt/cvda/animal3d/code/AnimalAvatar/cse_embedding/preprocess_cse.py", line 101, in preprocess_cse
    output = cse_processor.predict_batch(images_rgb)
  File "/mnt/cvda/animal3d/code/AnimalAvatar/cse_embedding/preprocess_cse.py", line 79, in predict_batch
    results = [self.predict_single(images_rgb[i]) for i in range(images_rgb.shape[0])]
  File "/mnt/cvda/animal3d/code/AnimalAvatar/cse_embedding/preprocess_cse.py", line 79, in <listcomp>
    results = [self.predict_single(images_rgb[i]) for i in range(images_rgb.shape[0])]
  File "/mnt/cvda/animal3d/code/AnimalAvatar/cse_embedding/preprocess_cse.py", line 60, in predict_single
    "E": outputs["instances"].pred_densepose.embedding.cpu(),
AttributeError: 'DensePoseChartPredictorOutputWithConfidences' object has no attribute 'embedding'
```

It seems to be some kind of environment problem, but I did install  python=3.10 | pytorch=2.0.1 | pytorch-cuda=11.8 and all the required dependencies. 

By the way, during preprocessing it is also reported that:
```
Some model parameters or buffers are not found in the checkpoint:
roi_heads.densepose_predictor.ann_index_lowres.{bias, weight}
roi_heads.densepose_predictor.index_uv_lowres.{bias, weight}
roi_heads.densepose_predictor.u_lowres.{bias, weight}
roi_heads.densepose_predictor.v_lowres.{bias, weight}
The checkpoint state_dict contains keys that are not used by the model:
  roi_heads.densepose_predictor.coarse_segm_lowres.{bias, weight}
  roi_heads.densepose_predictor.embed_lowres.{bias, weight}
```
Does it have anything to do with the attribute error?

**Comment by RemySabathier** [comment]
Hey,
I am not able to reproduce the error, can you share with me the exact command line you launch, and the version of detectron2-densepose in your environment ?
Also, for densepose-cse, please make sure you downloaded the exact model (model_final_8c9d99.pkl) and config files (Base-DensePose-RCNN-FPN.yaml) (densepose_rcnn_R_50_FPN_soft_animals_I0_finetune_i2m_16k.yaml) listed in the installation section.

**Comment by Gracezxw** [comment]
Thanks for the quick response!
I launched the command given in the README.md
```
#Example code to process the CoP3D sequence "1030_23106_17099"
python main_preprocess_scene.py -sequence_index "1030_23106_17099" --visualize
```
My detectron2-densepose version is 0.6, and I did download the required Densepose model weight and configs.
Does the version of detectron2-densepose differ from yours?

**Comment by RemySabathier** [comment]
Ok thanks, I'm using the same detectron2-densepose version, could you please post all the outputs you get when you launch the line :
python main_preprocess_scene.py -sequence_index "1030_23106_17099" --visualize

**Comment by Gracezxw** [comment]
Hey, 
I've solved the error by re-downloading the Densepose model weight and configs. Thank you very much for the  help!
