### ISSUE TITLE
About 2d keypoints.

### ISSUE THREAD

**Issue by LarkLeeOnePiece** [facebookresearch/AnimalAvatar#7]
Hello, for each frame how can you get the 2d keypoints for the dogs.  Did you use the dectron2 to get the keypoints?  Also, in the paper, you said, you seperated the shape fitting into two stages, at the first stage, you find a root pose first. Can you give more details about how to get the root pose. Which part of the code does this task?

Thanks!!

**Comment by LarkLeeOnePiece** [comment]
Also, how many keypoints that we can get from the dectron2?

**Comment by RemySabathier** [comment]
Hey,
the 2D sparse keypoints we propose for a subset of CoP3D scenes are extracted from the BITE model (https://github.com/runa91/bite_release). For the dense keypoints (CSE-embeddings) yes we use detectronv2.

**Comment by RemySabathier** [comment]
For the root pose, please refer to this part of the code: https://github.com/facebookresearch/AnimalAvatar/blob/9835a4a8b1b79d79b10ab288b921b287c71e7c6b/pnp/preprocess_pnp.py#L22
